In [1]:
#Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Load Dataset
data=pd.read_csv('./studentperf.csv')
data.head()

   Method  satis  time  ability  prvperf  Outcome
0       1      5    22       13     26.5        1
1       1      4    12       27     19.6        0
2       1      2    22       18     26.4        1
3       1      5    20       18     25.1        0
4       1      4    22       29     28.0        1

In [3]:
data.describe()

          Method      satis       time    ability    prvperf    Outcome
count  60.000000  60.000000  60.000000  60.000000  60.000000  60.000000
mean    2.000000   4.966667  18.533333  29.216667  22.796667   0.450000
std     0.823387   1.813010   3.586541  11.295854   3.262367   0.501692
min     1.000000   1.000000  12.000000   7.000000  16.000000   0.000000
25%     1.000000   4.000000  16.000000  22.000000  20.375000   0.000000
50%     2.000000   5.000000  18.000000  29.500000  22.700000   0.000000
75%     3.000000   6.000000  22.000000  37.250000  25.225000   1.000000
max     3.000000   9.000000  26.000000  49.000000  32.800000   1.000000

In [4]:
#Create X and Y variables
x=data.drop('Outcome', axis=1)
y=data['Outcome']

#Create Training and Test Datasets
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x, y, stratify=y,test_size=0.2,random_state=100)

#Scale the Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.fit_transform(x_test)

In [5]:
#Script for SVM and NB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix  

#we can use multiple model in the for loop
for name,method in [('Logistic Regression',LogisticRegression(solver='liblinear',random_state=100)),('SVM', SVC(kernel='linear',random_state=100)),
                    ('Naive Bayes',GaussianNB()),('Decision Tree', DecisionTreeClassifier(random_state=100))]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict))

Estimator: Logistic Regression
[[4 3]
 [4 1]]
              precision    recall  f1-score   support

           0       0.50      0.57      0.53         7
           1       0.25      0.20      0.22         5

    accuracy                           0.42        12
   macro avg       0.38      0.39      0.38        12
weighted avg       0.40      0.42      0.40        12


Estimator: SVM
[[4 3]
 [4 1]]
              precision    recall  f1-score   support

           0       0.50      0.57      0.53         7
           1       0.25      0.20      0.22         5

    accuracy                           0.42        12
   macro avg       0.38      0.39      0.38        12
weighted avg       0.40      0.42      0.40        12


Estimator: Naive Bayes
[[6 1]
 [3 2]]
              precision    recall  f1-score   support

           0       0.67      0.86      0.75         7
           1       0.67      0.40      0.50         5

    accuracy                           0.67        12
   macro avg       0.67      0.63      0.62        12
weighted avg       0.67      0.67      0.65        12


Estimator: Decision Tree
[[5 2]
 [3 2]]
              precision    recall  f1-score   support

           0       0.62      0.71      0.67         7
           1       0.50      0.40      0.44         5

    accuracy                           0.58        12
   macro avg       0.56      0.56      0.56        12
weighted avg       0.57      0.58      0.57        12